stream_list = [
    {
        "id": 1,
        "name": "First Stream", 
        "description": "Some kind of stream description",
        "img": None,
        "game": "Fortnite",
        "messages": [], # Each message should be a dict with sender, text, sender_color and stream_id
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Ninja",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 2,
        "name": "Second Stream", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Loeya",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 3,
        "name": "Third Stream", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Nick Eh 30",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 4,
        "name": "Fun Stuff", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Bugha",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 5,
        "name": "Games", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "dubz",
        "isRecommended": True,
        "isFollowed": False,
    },
    {
        "id": 6,
        "name": "Playing Around", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Jeff Bezos",
        "isRecommended": True,
        "isFollowed": False,
    },
    {
        "id": 7,
        "name": "Late Night Stream", 
        "description": "Some kind of stream description", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Last Streamer",
        "isRecommended": True,
        "isFollowed": False,
    },
]

recommended_streams = list(filter(lambda x: x["isRecommended"], stream_list))

streams_from_followed_channels = list(filter(lambda x: x["isFollowed"], stream_list))