stream_list = [
    {
        "id": 1,
        "name": "FNCS Finals", 
        "description": "Are we about to win fncs?",
        "img": None,
        "game": "Fortnite",
        "messages": [], # Each message should be a dict with sender, text, sender_color and stream_id
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Ninja",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 2,
        "name": "Duos with subs", 
        "description": "Just playing with subscribers", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Loeya",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 3,
        "name": "Practicing for World Cup", 
        "description": "Editing walls in creative faster than anyone else", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Nick Eh 30",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 4,
        "name": "Long Shot Challenge", 
        "description": "Only shooting from 200m", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Bugha",
        "isRecommended": False,
        "isFollowed": True,
    },
    {
        "id": 5,
        "name": "Getting the dubs", 
        "description": "20 win streak?!", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "dubz",
        "isRecommended": True,
        "isFollowed": False,
    },
    {
        "id": 6,
        "name": "Playing Around", 
        "description": "Playing some games", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Jeff Bezos",
        "isRecommended": True,
        "isFollowed": False,
    },
    {
        "id": 7,
        "name": "Mystery stream", 
        "description": "The mystery is slowly unwrapping", 
        "img": None,
        "game": "Fortnite",
        "messages": [],
        "isLive": False,
        "broadcasterId": None,
        "viewers": 0,
        "channelName": "Last Streamer",
        "isRecommended": True,
        "isFollowed": False,
    },
]

recommended_streams = list(filter(lambda x: x["isRecommended"], stream_list))

streams_from_followed_channels = list(filter(lambda x: x["isFollowed"], stream_list))

# Session id is key, displayed number is value
chat_users = {}

ping_words = ["Async", "generator", "is", "fetching", "paginated", "data"]